- name: Déployer WordPress avec Docker Compose
  hosts: ubuntu
  become: yes

  vars:
    wp_dir: /opt/wordpress
    mysql_root_password: rootpassword
    mysql_database: wordpress
    mysql_user: wpuser
    mysql_password: wppassword
    docker_compose_template_url: https://raw.githubusercontent.com/DB-Alexandre/CESI-ANSIBLE/main/templates/docker-compose.yml.j2

  tasks:
    - name: Vérifier les permissions du répertoire /opt
      file:
        path: /opt
        state: directory
        mode: '0755'

    - name: Créer le répertoire pour WordPress
      file:
        path: "{{ wp_dir }}"
        state: directory
        mode: '0755'

    - name: Vérifier que le répertoire WordPress existe
      stat:
        path: "{{ wp_dir }}"
      register: wp_dir_stat

    - name: Afficher le statut du répertoire WordPress
      debug:
        var: wp_dir_stat

    - name: Afficher le contenu du répertoire /opt/wordpress
      command: ls -la /opt/wordpress
      register: wp_contents

    - name: Afficher le contenu du répertoire /opt/wordpress
      debug:
        var: wp_contents.stdout_lines

    - name: Lancer WordPress avec Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ wp_dir }}"
        state: present
      when: wp_dir_stat.stat.exists and wp_dir_stat.stat.isdir
