- name: Déployer WordPress avec Docker Compose
  hosts: ubuntu
  become: yes

  vars:
    wp_dir: /opt/wordpress
    mysql_root_password: rootpassword
    mysql_database: wordpress
    mysql_user: wpuser
    mysql_password: wppassword

  tasks:
    - name: Installer les dépendances nécessaires
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Installer Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Activer et démarrer le socket Docker
      systemd:
        name: docker.socket
        enabled: yes
        state: started

    - name: Redémarrer le service Docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

    - name: Installer Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Créer le répertoire pour WordPress
      file:
        path: "{{ wp_dir }}"
        state: directory
        mode: '0755'

    - name: Vérifier que le répertoire WordPress existe
      stat:
        path: "{{ wp_dir }}"
      register: wp_dir_stat

    - name: Afficher le statut du répertoire WordPress
      debug:
        var: wp_dir_stat

    - name: Créer docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ wp_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Lancer WordPress avec Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ wp_dir }}"
        state: present
      when: wp_dir_stat.stat.isdir is defined and wp_dir_stat.stat.isdir
