- name: Déployer WordPress avec Docker Compose
  hosts: ubuntu
  become: yes

  vars:
    wp_dir: /opt/wordpress
    mysql_root_password: rootpassword
    mysql_database: wordpress
    mysql_user: wpuser
    mysql_password: wppassword
    docker_compose_template_url: https://raw.githubusercontent.com/DB-Alexandre/CESI-ANSIBLE/main/templates/docker-compose.yml.j2

  tasks:
    - name: Vérifier les permissions du répertoire /opt
      file:
        path: /opt
        state: directory
        mode: '0755'

    - name: Créer le répertoire pour WordPress
      file:
        path: "{{ wp_dir }}"
        state: directory
        mode: '0755'

    - name: Télécharger le template docker-compose.yml.j2 depuis GitHub
      get_url:
        url: "{{ docker_compose_template_url }}"
        dest: "{{ wp_dir }}/docker-compose.yml.j2"
        mode: '0644'

    - name: Installer pip3 s’il n’est pas présent
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Installer jinja2-cli via pip
      ansible.builtin.pip:
        name: jinja2-cli
        executable: pip3

    - name: Générer un fichier vars.json pour Jinja2
      copy:
        content: "{{ vars | to_json }}"
        dest: "{{ wp_dir }}/vars.json"
        mode: '0644'

    - name: Rendre le template docker-compose.yml avec jinja2-cli
      shell: |
        jinja2 {{ wp_dir }}/docker-compose.yml.j2 {{ wp_dir }}/vars.json > {{ wp_dir }}/docker-compose.yml
      args:
        executable: /bin/bash

    - name: Supprimer le fichier vars.json (optionnel)
      file:
        path: "{{ wp_dir }}/vars.json"
        state: absent

    - name: Vérifier que le fichier docker-compose.yml existe
      stat:
        path: "{{ wp_dir }}/docker-compose.yml"
      register: wp_compose_file

    - name: Debug fichier généré
      debug:
        var: wp_compose_file.stat.exists

    - name: Lancer WordPress avec Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ wp_dir }}"
        state: present
      when: wp_compose_file.stat.exists
